# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1221, 770)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QmainWindow{\n"
"    background-color:black\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1221, 771))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    writing-mode: horizontal-tb;  /* Forces horizontal text */\n"
"    height: 50px;  /* Adjust height */\n"
"    padding: 5px;\n"
"    \n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.home_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_tab.sizePolicy().hasHeightForWidth())
        self.home_tab.setSizePolicy(sizePolicy)
        self.home_tab.setObjectName("home_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.home_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.home_left_frame = QtWidgets.QFrame(parent=self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_left_frame.sizePolicy().hasHeightForWidth())
        self.home_left_frame.setSizePolicy(sizePolicy)
        self.home_left_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.home_left_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.home_left_frame.setObjectName("home_left_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.home_left_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.greet_label = QtWidgets.QLabel(parent=self.home_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greet_label.sizePolicy().hasHeightForWidth())
        self.greet_label.setSizePolicy(sizePolicy)
        self.greet_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 30px;\n"
"    font-weight:bold;\n"
"}")
        self.greet_label.setObjectName("greet_label")
        self.verticalLayout.addWidget(self.greet_label)
        self.quick_scan_label = QtWidgets.QLabel(parent=self.home_left_frame)
        self.quick_scan_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 50px;\n"
"    font-weight:bold;\n"
"}")
        self.quick_scan_label.setObjectName("quick_scan_label")
        self.verticalLayout.addWidget(self.quick_scan_label)
        self.url_horizontalLayout = QtWidgets.QHBoxLayout()
        self.url_horizontalLayout.setContentsMargins(-1, 11, 0, 1)
        self.url_horizontalLayout.setObjectName("url_horizontalLayout")
        self.url_lineEdit = QtWidgets.QLineEdit(parent=self.home_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_lineEdit.sizePolicy().hasHeightForWidth())
        self.url_lineEdit.setSizePolicy(sizePolicy)
        self.url_lineEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.url_lineEdit.setStyleSheet("QLineEdit {\n"
"    border: solid;\n"
"    border-radius: 18px;\n"
"    border-width: 0.5px;\n"
"    border-color: grey;\n"
"    padding-left: 20px;        \n"
"    padding-right: 20px;\n"
"    font-size:25px;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px\n"
"}")
        self.url_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.url_horizontalLayout.addWidget(self.url_lineEdit)
        self.verticalLayout.addLayout(self.url_horizontalLayout)
        self.button_horizontalLayout = QtWidgets.QHBoxLayout()
        self.button_horizontalLayout.setContentsMargins(-1, 11, 11, 1)
        self.button_horizontalLayout.setObjectName("button_horizontalLayout")
        self.quick_scan_pushButton = QtWidgets.QPushButton(parent=self.home_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quick_scan_pushButton.sizePolicy().hasHeightForWidth())
        self.quick_scan_pushButton.setSizePolicy(sizePolicy)
        self.quick_scan_pushButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(35, 222, 104);\n"
"    color: white;\n"
"    border: solid;\n"
"    border-radius: 20px;\n"
"    border-width: 0.1px;\n"
"    transition: all 0.2s ease;\n"
"    font-size:25px;\n"
"    font-weight:bold;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"    padding-right: 30px;\n"
"    padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #27ae60;  /* Darker green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449;\n"
"    transform: scale(0.95);  /* Slight shrink effect */\n"
"}")
        self.quick_scan_pushButton.setObjectName("quick_scan_pushButton")
        self.button_horizontalLayout.addWidget(self.quick_scan_pushButton)
        self.verticalLayout.addLayout(self.button_horizontalLayout)
        self.quick_scan_output_textBrowser = QtWidgets.QTextBrowser(parent=self.home_left_frame)
        self.quick_scan_output_textBrowser.setObjectName("quick_scan_output_textBrowser")
        self.verticalLayout.addWidget(self.quick_scan_output_textBrowser)
        self.generate_report_horizontalLayout = QtWidgets.QHBoxLayout()
        self.generate_report_horizontalLayout.setContentsMargins(-1, 11, -1, -1)
        self.generate_report_horizontalLayout.setObjectName("generate_report_horizontalLayout")
        self.generate_full_scan_report_pushButton = QtWidgets.QPushButton(parent=self.home_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_full_scan_report_pushButton.sizePolicy().hasHeightForWidth())
        self.generate_full_scan_report_pushButton.setSizePolicy(sizePolicy)
        self.generate_full_scan_report_pushButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(35, 222, 104);\n"
"    color: white;\n"
"    border: solid;\n"
"    border-radius: 20px;\n"
"    border-width: 0.1px;\n"
"    transition: all 0.2s ease;\n"
"    font-size:25px;\n"
"    font-weight:bold;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"    padding-right: 30px;\n"
"    padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #27ae60;  /* Darker green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449;\n"
"    transform: scale(0.95);  /* Slight shrink effect */\n"
"}")
        self.generate_full_scan_report_pushButton.setObjectName("generate_full_scan_report_pushButton")
        self.generate_report_horizontalLayout.addWidget(self.generate_full_scan_report_pushButton)
        self.verticalLayout.addLayout(self.generate_report_horizontalLayout)
        self.horizontalLayout.addWidget(self.home_left_frame)
        self.home_right_frame = QtWidgets.QFrame(parent=self.home_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_right_frame.sizePolicy().hasHeightForWidth())
        self.home_right_frame.setSizePolicy(sizePolicy)
        self.home_right_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.home_right_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.home_right_frame.setObjectName("home_right_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.home_right_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.security_tip_label = QtWidgets.QLabel(parent=self.home_right_frame)
        self.security_tip_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.security_tip_label.setObjectName("security_tip_label")
        self.verticalLayout_2.addWidget(self.security_tip_label)
        self.num_of_quick_scan_label = QtWidgets.QLabel(parent=self.home_right_frame)
        self.num_of_quick_scan_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.num_of_quick_scan_label.setObjectName("num_of_quick_scan_label")
        self.verticalLayout_2.addWidget(self.num_of_quick_scan_label)
        self.history_quick_scan_label = QtWidgets.QLabel(parent=self.home_right_frame)
        self.history_quick_scan_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.history_quick_scan_label.setObjectName("history_quick_scan_label")
        self.verticalLayout_2.addWidget(self.history_quick_scan_label)
        self.history_quick_scan_textBrowser = QtWidgets.QTextBrowser(parent=self.home_right_frame)
        self.history_quick_scan_textBrowser.setObjectName("history_quick_scan_textBrowser")
        self.verticalLayout_2.addWidget(self.history_quick_scan_textBrowser)
        self.view_full_scan_history_horizontalLayout = QtWidgets.QHBoxLayout()
        self.view_full_scan_history_horizontalLayout.setContentsMargins(-1, 11, -1, -1)
        self.view_full_scan_history_horizontalLayout.setObjectName("view_full_scan_history_horizontalLayout")
        self.view_full_scan_history_pushButton_2 = QtWidgets.QPushButton(parent=self.home_right_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_full_scan_history_pushButton_2.sizePolicy().hasHeightForWidth())
        self.view_full_scan_history_pushButton_2.setSizePolicy(sizePolicy)
        self.view_full_scan_history_pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color:rgb(35, 222, 104);\n"
"    color: white;\n"
"    border: solid;\n"
"    border-radius: 20px;\n"
"    border-width: 0.1px;\n"
"    transition: all 0.2s ease;\n"
"    font-size:25px;\n"
"    font-weight:bold;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 10px;\n"
"    padding-right: 30px;\n"
"    padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #27ae60;  /* Darker green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449;\n"
"    transform: scale(0.95);  /* Slight shrink effect */\n"
"}")
        self.view_full_scan_history_pushButton_2.setObjectName("view_full_scan_history_pushButton_2")
        self.view_full_scan_history_horizontalLayout.addWidget(self.view_full_scan_history_pushButton_2)
        self.verticalLayout_2.addLayout(self.view_full_scan_history_horizontalLayout)
        self.horizontalLayout.addWidget(self.home_right_frame)
        self.tabWidget.addTab(self.home_tab, "")

        
        #About Tab
        self.about_tab = QtWidgets.QWidget()
        self.about_tab.setObjectName("about_tab")
        self.about_tab_scrollArea = QtWidgets.QScrollArea(parent=self.about_tab)
        self.about_tab_scrollArea.setGeometry(QtCore.QRect(0, 10, 1191, 751))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_tab_scrollArea.sizePolicy().hasHeightForWidth())
        self.about_tab_scrollArea.setSizePolicy(sizePolicy)
        self.about_tab_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.about_tab_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.about_tab_scrollArea.setWidgetResizable(True)
        self.about_tab_scrollArea.setObjectName("about_tab_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1189, 749))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.about_tab_scrollArea_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_tab_scrollArea_2.sizePolicy().hasHeightForWidth())
        self.about_tab_scrollArea_2.setSizePolicy(sizePolicy)
        self.about_tab_scrollArea_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.about_tab_scrollArea_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.about_tab_scrollArea_2.setObjectName("about_tab_scrollArea_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.about_tab_scrollArea_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.about_app_label = QtWidgets.QLabel(parent=self.about_tab_scrollArea_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_app_label.sizePolicy().hasHeightForWidth())
        self.about_app_label.setSizePolicy(sizePolicy)
        self.about_app_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 30px;\n"
"    font-weight:bold;\n"
"}")
        self.about_app_label.setText("")
        self.about_app_label.setObjectName("about_app_label")
        self.verticalLayout_10.addWidget(self.about_app_label)
        self.verticalLayout_9.addWidget(self.about_tab_scrollArea_2)
        self.about_tab_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.about_tab, "")
        self.profile_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_tab.sizePolicy().hasHeightForWidth())
        self.profile_tab.setSizePolicy(sizePolicy)

        #Profile Tab
        self.profile_tab.setObjectName("profile_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.profile_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.profile_tab_left_frame = QtWidgets.QFrame(parent=self.profile_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_tab_left_frame.sizePolicy().hasHeightForWidth())
        self.profile_tab_left_frame.setSizePolicy(sizePolicy)
        self.profile_tab_left_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.profile_tab_left_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.profile_tab_left_frame.setObjectName("profile_tab_left_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.profile_tab_left_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.username_label = QtWidgets.QLabel(parent=self.profile_tab_left_frame)
        self.username_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.username_label.setObjectName("username_label")
        self.verticalLayout_7.addWidget(self.username_label)
        self.email_label = QtWidgets.QLabel(parent=self.profile_tab_left_frame)
        self.email_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.email_label.setObjectName("email_label")
        self.verticalLayout_7.addWidget(self.email_label)
        self.time_date_acc_created_label = QtWidgets.QLabel(parent=self.profile_tab_left_frame)
        self.time_date_acc_created_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.time_date_acc_created_label.setObjectName("time_date_acc_created_label")
        self.verticalLayout_7.addWidget(self.time_date_acc_created_label)
        self.last_login_date_time_label = QtWidgets.QLabel(parent=self.profile_tab_left_frame)
        self.last_login_date_time_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.last_login_date_time_label.setObjectName("last_login_date_time_label")
        self.verticalLayout_7.addWidget(self.last_login_date_time_label)
        self.log_out_pushButton = QtWidgets.QPushButton(parent=self.profile_tab_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_out_pushButton.sizePolicy().hasHeightForWidth())
        self.log_out_pushButton.setSizePolicy(sizePolicy)
        self.log_out_pushButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(35, 222, 104);\n"
"    color: white;\n"
"    border: solid;\n"
"    border-radius: 20px;\n"
"    border-width: 0.1px;\n"
"    transition: all 0.2s ease;\n"
"    font-size:25px;\n"
"    font-weight:bold;\n"
"    padding: 10px 5px;\n"
"    padding-right: 30px;\n"
"    padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #27ae60;  /* Darker green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449;\n"
"    transform: scale(0.95);  /* Slight shrink effect */\n"
"}")
        self.log_out_pushButton.setObjectName("log_out_pushButton")
        self.verticalLayout_7.addWidget(self.log_out_pushButton)
        self.delete_account_pushButton = QtWidgets.QPushButton(parent=self.profile_tab_left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_account_pushButton.sizePolicy().hasHeightForWidth())
        self.delete_account_pushButton.setSizePolicy(sizePolicy)
        self.delete_account_pushButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(35, 222, 104);\n"
"    color: white;\n"
"    border: solid;\n"
"    border-radius: 20px;\n"
"    border-width: 0.1px;\n"
"    transition: all 0.2s ease;\n"
"    font-size:25px;\n"
"    font-weight:bold;\n"
"    padding: 10px 5px;\n"
"    padding-right: 30px;\n"
"    padding-left: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #27ae60;  /* Darker green */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e8449;\n"
"    transform: scale(0.95);  /* Slight shrink effect */\n"
"}")
        self.delete_account_pushButton.setObjectName("delete_account_pushButton")
        self.verticalLayout_7.addWidget(self.delete_account_pushButton)
        self.horizontalLayout_4.addWidget(self.profile_tab_left_frame)
        self.profile_tab_right_frame = QtWidgets.QFrame(parent=self.profile_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_tab_right_frame.sizePolicy().hasHeightForWidth())
        self.profile_tab_right_frame.setSizePolicy(sizePolicy)
        self.profile_tab_right_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.profile_tab_right_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.profile_tab_right_frame.setObjectName("profile_tab_right_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.profile_tab_right_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.num_of_full_scan_label = QtWidgets.QLabel(parent=self.profile_tab_right_frame)
        self.num_of_full_scan_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.num_of_full_scan_label.setObjectName("num_of_full_scan_label")
        self.verticalLayout_8.addWidget(self.num_of_full_scan_label)
        self.num_of_custom_scan_label_2 = QtWidgets.QLabel(parent=self.profile_tab_right_frame)
        self.num_of_custom_scan_label_2.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.num_of_custom_scan_label_2.setObjectName("num_of_custom_scan_label_2")
        self.verticalLayout_8.addWidget(self.num_of_custom_scan_label_2)
        self.num_of_total_scan_label = QtWidgets.QLabel(parent=self.profile_tab_right_frame)
        self.num_of_total_scan_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.num_of_total_scan_label.setObjectName("num_of_total_scan_label")
        self.verticalLayout_8.addWidget(self.num_of_total_scan_label)
        self.num_of_total_vulnerabilities_label = QtWidgets.QLabel(parent=self.profile_tab_right_frame)
        self.num_of_total_vulnerabilities_label.setStyleSheet("QLabel{\n"
"    color:black;\n"
"    font-size: 20px;\n"
"    font-weight:bold;\n"
"}")
        self.num_of_total_vulnerabilities_label.setObjectName("num_of_total_vulnerabilities_label")
        self.verticalLayout_8.addWidget(self.num_of_total_vulnerabilities_label)
        self.vulnerabilties_pie_chart_graphicsView = QtWidgets.QGraphicsView(parent=self.profile_tab_right_frame)
        self.vulnerabilties_pie_chart_graphicsView.setObjectName("vulnerabilties_pie_chart_graphicsView")
        self.verticalLayout_8.addWidget(self.vulnerabilties_pie_chart_graphicsView)
        self.terms_and_conditions_commandLinkButton = QtWidgets.QCommandLinkButton(parent=self.profile_tab_right_frame)
        self.terms_and_conditions_commandLinkButton.setStyleSheet("QCommandLinkButton {\n"
"    color: black;\n"
"    qproperty-icon: none;\n"
"    font: Nirmala text;\n"
"    font-size: 16px;\n"
"    font-weight:bold;\n"
"    text-decoration: underline;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.terms_and_conditions_commandLinkButton.setObjectName("terms_and_conditions_commandLinkButton")
        self.verticalLayout_8.addWidget(self.terms_and_conditions_commandLinkButton)
        self.horizontalLayout_4.addWidget(self.profile_tab_right_frame)
        self.tabWidget.addTab(self.profile_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.custom_scan_selector_comboBox.setCurrentIndex(0)
        self.clear_history_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.greet_label.setText(_translate("MainWindow", "Good"))
        self.quick_scan_label.setText(_translate("MainWindow", "Quick Scan"))
        self.url_lineEdit.setPlaceholderText(_translate("MainWindow", "enter url"))
        self.quick_scan_pushButton.setText(_translate("MainWindow", "Full Scan"))
        self.generate_full_scan_report_pushButton.setText(_translate("MainWindow", "Generate Detailed Report"))
        self.security_tip_label.setText(_translate("MainWindow", "Tip of the Day:"))
        self.num_of_quick_scan_label.setText(_translate("MainWindow", "Total No. of full scans:"))
        self.history_quick_scan_label.setText(_translate("MainWindow", "History of full scans:"))
        self.view_full_scan_history_pushButton_2.setText(_translate("MainWindow", "View Full Scan History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home_tab), _translate("MainWindow", "Home"))
        self.custom_scan_label.setText(_translate("MainWindow", "Custom Scan"))
        self.custom_scan_lineEdit.setPlaceholderText(_translate("MainWindow", "enter url"))
        self.custom_scan_selector_comboBox.setCurrentText(_translate("MainWindow", "http scan"))
        self.custom_scan_selector_comboBox.setItemText(0, _translate("MainWindow", "http scan"))
        self.custom_scan_selector_comboBox.setItemText(1, _translate("MainWindow", "sql-injection"))
        self.custom_scan_selector_comboBox.setItemText(2, _translate("MainWindow", "xss-injection"))
        self.custom_scan_selector_comboBox.setItemText(3, _translate("MainWindow", "broken authentication"))
        self.custom_scan_selector_comboBox.setItemText(4, _translate("MainWindow", "csrf scan"))
        self.custom_scan_pushButton.setText(_translate("MainWindow", "Custom Scan"))
        self.generate_custom_scan_report_pushButton.setText(_translate("MainWindow", "Generate Detailed Report"))
        self.reset_scanner_pushButton.setText(_translate("MainWindow", "Reset Scanners"))
        self.num_of_custom_scan_label.setText(_translate("MainWindow", "Total No. of Custom Scans:"))
        self.custom_scan_history_label.setText(_translate("MainWindow", "History of custom scans:"))
        self.view_custom_scan_history_pushButton_2.setText(_translate("MainWindow", "View Custom Scan History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.custom_scan_tab), _translate("MainWindow", "Custom Scan"))
        self.search_history_label.setText(_translate("MainWindow", "Search History"))
        self.search_history_lineEdit.setPlaceholderText(_translate("MainWindow", "enter url"))
        self.view_full_scan_history_pushButton.setText(_translate("MainWindow", "View Full Scan History"))
        self.view_custom_scan_history_pushButton.setText(_translate("MainWindow", "View Custom Scan History"))
        self.clear_history_comboBox.setCurrentText(_translate("MainWindow", "Delete Full Scan History"))
        self.clear_history_comboBox.setItemText(0, _translate("MainWindow", "Delete Full Scan History"))
        self.clear_history_comboBox.setItemText(1, _translate("MainWindow", "Delete Custom Scan History"))
        self.clear_history_comboBox.setItemText(2, _translate("MainWindow", "Delete everything"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.history_tab), _translate("MainWindow", "History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about_tab), _translate("MainWindow", "About"))
        self.username_label.setText(_translate("MainWindow", "Userrname:"))
        self.email_label.setText(_translate("MainWindow", "Email:"))
        self.time_date_acc_created_label.setText(_translate("MainWindow", "Time and Date of last login:"))
        self.last_login_date_time_label.setText(_translate("MainWindow", "Account created at"))
        self.log_out_pushButton.setText(_translate("MainWindow", "Log Out"))
        self.delete_account_pushButton.setText(_translate("MainWindow", "Delete Account"))
        self.num_of_full_scan_label.setText(_translate("MainWindow", "No. of full scans:"))
        self.num_of_custom_scan_label_2.setText(_translate("MainWindow", "No. of custom scans:"))
        self.num_of_total_scan_label.setText(_translate("MainWindow", "Total no. of vulnerabilities found:"))
        self.num_of_total_vulnerabilities_label.setText(_translate("MainWindow", "Pie chart for percentage of each vulnerability"))
        self.terms_and_conditions_commandLinkButton.setText(_translate("MainWindow", "terms and conditions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profile_tab), _translate("MainWindow", "Profile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
